const mockdata = {
  recipesList: [
    {
      id: 'recipe01',
      recipeName: 'Snicker Doodles',
      time: 38,
      difficulty: 2,
      ingredients: [
        [120, 'g', 'vegetable margarine'],
        [60, 'g', 'cane sugar'],
        [1, 'teaspoon', 'vanilla extract'],
        [220, 'g', 'wheat flour (type 550)'],
        [10, 'g', 'cornstarch'],
        [1, 'teaspoon', 'baking powder'],
        [0.5, 'teaspoon', 'soda'],
        [4, 'tablespoons', 'vegetable milk or water'],
        [2, 'tablespoons', 'cane sugar'],
        [0.75, 'teaspoon', 'cinnamon'],
      ],
      shortDescription: [
        '1. Put the margarine and 60 g sugar in a mixing bowl and beat until fluffy with a hand mixer or a food processor.',
        '2. Sift flour, starch, baking soda and baking soda in a second mixing bowl and mix gently.',
        '3.  Add the flour mixture slowly to the margarine. Add vanilla extract and vegetable milk / water and mix it again.',
        '4. Preheat oven to 175ºC top / bottom heat.',
        '5. Mix cinnamon and the rest of sugar for the cinnamon-sugar mixture in a small bowl.',
        '6. Now form balls from the dough that have a diameter of about 3.5cm and roll in cinnamon-sugar mixture.',
        '7. Place the balls approx. 6cm apart from each other on a baking tray lined with a reusable baking mat or baking paper and flatten with the palm of the hand.',
        '8. Bake in the oven on a medium rack for about 8-10 minutes. Afterwards let them cool down.',
      ],
      tags: ['vegan', 'sweet', 'everyday classic'],
      titleImage: '/images/SnickerDoodles.jpg',
    },
    {
      id: 'recipe02',
      recipeName: 'Estonian Spring Cake',
      time: 150,
      difficulty: 4,
      ingredients: [
        [250, 'g', 'wheat flour (type 550)'],
        [150, 'g', 'butter'],
        [75, 'g', 'cane sugar'],
        [1, '', 'egg'],
        [1, 'pinch', 'salt'],
        [500, 'g', 'rhubarb'],
        [5, 'tabelspoons', 'cane sugar'],
        [1, 'tabelspoon', 'cinnamon'],
        [4, '', 'eggs'],
        [4, 'tabelspoons', 'wheat flour (type 405)'],
        [4, 'tabelspoons', 'white sugar'],
      ],
      shortDescription: [
        '1. Mix 250g of flour, butter, 75g of cane sugar, one egg and a pinch of salt. Knead the dough fast and thoroughly. Place it in the fridge for one hour.',
        '2. Wash, peel and chop the rhubarb.',
        '3. Preheat oven to 180ºC',
        '4. Enrobe the cake pan with dough and bake it in the oven with a coverage of dried peas for approximately 15 minutes.',
        '5. Seperate 4 eggyolks from the whites.',
        '6. Whisk the whites to a very firm foam and add the white sugar.',
        '7. Mix the yolks and the other amount of flour thoroughly.',
        '8. Cover the baked bottom with rhubarb pieces, sprinkle with the other amount of cane sugar and cinnamon.',
        '9. Mix the eggwhites and the yolks carefully. Pour it over the bottom and rhubarb.',
        '10. Bake the cake for approximately 50-60 minutes. Check it with a wooden stick.',
      ],
      tags: ['sweet', 'spring'],
      titleImage: '/images/rhabarber.jpg',
    },
    {
      id: 'recipe03',
      recipeName: 'Cheese Oat Biscuits',
      time: 45,
      difficulty: 1,
      ingredients: [
        [90, 'g', 'oatmeal'],
        [50, 'g', 'wheat flour (type 550)'],
        [2, 'tabelspoons', 'milk'],
        [0.5, 'teaspoon', 'baking powder'],
        [3, 'tabelspoons', 'grated cheese'],
        [50, 'g', 'butter'],
        [1, '', 'eggyolk'],
      ],
      shortDescription: [
        '1. Preheat the oven to 160°C.',
        '2. Mix all ingredients except the yolk until firm.',
        '3. Firl the pastry 2-3 cm thick and cut it into small circles.',
        '4. Place the circles on a baking tray and smear them with yolk.',
        '5. Bake the biscuits 10-15 minutes.',
      ],
      tags: ['everyday classic', 'hearty'],
      titleImage: '/images/kaesekekse.jpg',
    },
  ],
}
export default mockdata
